name = "studio/token-distribution"
version = "0.0.0"
compiler = "v1.1.21"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'studio/token-distribution'"

[repository]
user = "studio"
project = "token-distribution"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "2.2.0"
source = "github"
